### ISSUE TITLE
Will not attack tentacles in Maw of Souls Helya fight

### ISSUE THREAD

**Issue by Baconadors** [CuteOne/BadRotations#134]
I have noticed this on my DK and Warlock.
On the Helya fight in Maw of Souls (any difficulty) the the destructor and grasping tentacles will not be attacked with either rotation. I suspect this is also true of all other classes.

However Helya WILL be attacked during the last phase of the fight.

**Comment by Druxlolz** [comment]
This is duo to firehack nothing with badrotations for what i understand should be some beta builds out on his discord where it works :)

**Comment by Baconadors** [comment]
Good to hear. Thank you.

**Comment by kuukuukuatchu** [comment]
Sounds like you're not using the most up to date badrotations.  I patched the fh object position issue almost a week ago. What version does your toc file say you have?

**Comment by Baconadors** [comment]
Version: 1.6.5
I just updated to the latest version, 1.7.0. I'll report back on it. Thanks!

**Comment by Aleksaas** [comment]
I also noticed this issue, and when I did some logging I noticed getDistance('target') returns a distance of above 3000. The onlt FH function it uses is function ObjectPosition (Object), so that function is the problem? I will use this thread to ask one question to devs if possible. How do you achieve that, for instance, when I use heroic leap as fury warrior it doesnt break when bot is casting spells. When I modified rotation and made my own (deleted lot of stuffs I dont need), then I have a problem that green circle on ground for leap disappears when bot casts any spell...

**Comment by CuteOne** [comment]
I can attest EWT does not have range problems

**Comment by kuukuukuatchu** [comment]
You shouldn't even see the green circle if your code is working properly.  Green circle means it's casting but not clicking for ground target.

**Comment by Aleksaas** [comment]
I found the solution. I use function SpellIsTargeting() and if it is true I dont proceed further, which means bot is paused while I use Heroic Leap.

**Comment by Baconadors** [comment]
Just ran MoS for the first time since I opened the issue. Fixed with the latest update.
